spring.application.name=examenMau

spring.datasource.url=jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=estudiante
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect   
spring.jpa.hibernate.ddl-auto=update